services:
  db:
    image: postgres:16
    container_name: go_proj_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-app}"]
      interval: 3s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_proj_api
    environment:
      PORT: "8080"
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: ${POSTGRES_DB:-app}
      DB_USER: ${POSTGRES_USER:-app}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-app}
      DB_SSLMODE: "disable"
      DATABASE_URL: "postgres://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@db:5432/${POSTGRES_DB:-app}?sslmode=disable"
      WORKER_COUNT: "5"
      JOB_CHANNEL_BUFFER: "5"
      POLL_INTERVAL: "2s"
    ports:
      - "8081:8080"
    stop_grace_period: 30s
    depends_on:
      db:
        condition: service_healthy
    command: ["./server"]

volumes:
  pgdata:
