services:
  redis:
    image: redis:7-alpine
    container_name: go_proj_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 10

  db:
    image: postgres:16
    container_name: go_proj_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-app}"]
      interval: 3s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_proj_api
    environment:
      PORT: "8080"
      DATABASE_URL: "postgres://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@db:5432/${POSTGRES_DB:-app}?sslmode=disable"
      REDIS_URL: "redis://redis:6379"
      QUEUE_PENDING_KEY: "jobs:pending"
      QUEUE_PROCESSING_KEY: "jobs:processing"
      QUEUE_CLAIM_TIMEOUT: "5s"
    ports:
      - "8081:8080"
    stop_grace_period: 30s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["./api"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_proj_worker
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@db:5432/${POSTGRES_DB:-app}?sslmode=disable"
      REDIS_URL: "redis://redis:6379"
      QUEUE_PENDING_KEY: "jobs:pending"
      QUEUE_PROCESSING_KEY: "jobs:processing"
      QUEUE_CLAIM_TIMEOUT: "5s"
      WORKER_COUNT: "5"
      JOB_CHANNEL_BUFFER: "5"
      POLL_INTERVAL: "2s"
      STUCK_JOB_TIMEOUT: "30s"
      REAPER_INTERVAL: "10s"
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    stop_grace_period: 30s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["./worker"]

volumes:
  pgdata:
